name: enigma_collapse

networks:
  common:

volumes:
  postgres:
  kafka:
  qdrant:

services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-enigma}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_USER=${POSTGRES_USER:-user}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql
    networks:
      - common

  kafka:
    image: apache/kafka-native:4.1.1
    restart: unless-stopped
    hostname: kafka
    user: root
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka:19092
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:29093
      - KAFKA_LISTENERS=CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - CLUSTER_ID=4L6g3nShT-eMCtK--X86sw
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR=1
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
    ports:
      - '9092:9092'
    volumes:
      - kafka:/var/lib/kafka/data
    networks:
      - common

  qdrant:
    image: qdrant/qdrant:v1
    restart: unless-stopped
#    environment:
#      - QDRANT__TLS__ENABLED=false
    ports:
      - '6333:6333' # localhost:6333/dashboard
      - '6334:6334' # grpc
    volumes:
      - qdrant:/qdrant/storage

  xray:
    image: teddysun/xray:26.2.6
    restart: unless-stopped
    command: xray -c /etc/xray/config.json
    volumes:
      - ./config-vpn.json:/etc/xray/config.json
    ports:
      - "127.0.0.1:2088:2080" # Порт в inbound конфига должен совпадать

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-enigma}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}

      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS:-kafka:19092}

      - MAIL_USERNAME=require_ask_in_chat
      - MAIL_PASSWORD=require_ask_in_chat
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - common
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - common
