spring:
  application:
    name: enigma
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:enigma}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: enigma-collapse-backend
      auto-offset-reset: latest


mail:
  imap-host: imap.mail.ru
  imap-port: 993
  smtp-host: smtp.mail.ru
  smtp-port: 465
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
