spring:
  application:
    name: enigma
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:enigma}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: enigma-collapse-backend
      auto-offset-reset: latest


mail:
  imap-host: imap.mail.ru
  imap-port: 993
  smtp-host: smtp.mail.ru
  smtp-port: 465
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}

openrouter:
  api-key: ${OPENROUTER_API_KEY:REQUIRED}
  base-url: https://openrouter.ai/api/v1
  model-embedding: openai/text-embedding-3-small
  model-llm: x-ai/grok-4.1-fast

qdrant:
  host: ${QDRANT_URL:localhost}
  port: ${QDRANT_PORT:6334}
  collection: ${QDRANT_COLLECTION:enigma_hack}

xray:
  host: ${XRAY_HOST:localhost}
  port: ${XRAY_PORT:2080}

